version: '3'

services:
    web:
        build: .
        volumes:
          - ./src/eiprice_scraping_poc:/app
        ports:
          - "8080:5000"
        environment:
          FLASK_APP: app/main.py
          FLASK_DEBUG: 1
          MONGODB_DB: flaskdb
          MONGODB_HOST: mongodb
          MONGODB_PORT: 27017
          MONGODB_USERNAME: flaskuser
          MONGODB_PASSWORD: your_mongodb_password
          RUN: flask run --host=0.0.0.0 --port=5000
        networks:
            - frontend
            - backend
    mongodb:
        image: mongo:4.0.8
        ports:
          - "27017:27017"
        container_name: mongodb
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongodbuser
            MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
            MONGO_INITDB_DATABASE: flaskdb
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        volumes:
            - mongodbdata:/data/db
        networks:
            - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
