version: '3.4'

services:
    web:
        build: .
        volumes:
          - ./src/app:/app
        ports:
          - "5000:5000"
        environment:
          FLASK_APP: app/main.py
          FLASK_DEBUG: 1
          MONGODB_DB: eiprice
          MONGODB_HOST: localhost
          MONGODB_PORT: 27017
          RUN: flask fetch_data && flask run --host=0.0.0.0 --port=5000
        networks:
            - frontend
            - backend
    mongodb:
        image: mongo:4.2
        ports:
          - "27017:27017"
        container_name: mongodb
        restart: unless-stopped
        environment:
          MONGODB_DATA_DIR: /data/db
          MONDODB_LOG_DIR: /dev/null
        volumes:
            - mongodbdata:/data/db
        networks:
            - frontend
            - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
